todo-deploy: fixed test

diff --git a/.github/workflows/terraform-validate.yml b/.github/workflows/terraform-validate.yml
--- a/.github/workflows/terraform-validate.yml
+++ b/.github/workflows/terraform-validate.yml
@@ -30,13 +30,13 @@ jobs:
     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v3
 
-    - name: Check resource group configuration
+    - name: Check resource group data source
       run: |
-        if ! grep -q 'resource "azurerm_resource_group"' main.tf; then
-          echo "Resource group configuration not found in main.tf!"
+        if ! grep -q 'data "azurerm_resource_group"' main.tf; then
+          echo "Resource group data source not found in main.tf!"
           exit 1
         fi
-        echo "Resource group configuration is present."
+        echo "Resource group data source is present."
 
     - name: Check storage account configuration
       run: |
